### ISSUE TITLE
From OpenZeppelin: Nice code!

### ISSUE THREAD

**Issue by dbessinOZ** [luisivan/solarguild.xyz#1]
Hey Luis, I'm with OpenZeppelin helping build our tech teams. I would imagine you're comfortable doing what you do now with Nation3 - in the spirit of being thorough with my job, though, I wanted to gauge your interest in potentially joining our audit/research team and audit some of the biggest web3 protocols in the ecosystem. If not, no worries and thank you for all that you contribute to the space 🙂

**Comment by luisivan** [comment]
Say hi to Demian and Marto!
